export interface MobileImage {
  id: number;
  black: string;
  color: string;
  alt: string;
  width: number;
  height: number;
  active: boolean;
}

const imageHeight = 422;

export const mobileImages: MobileImage[] = [
  {
    id: 1,
    black: "01-SmallBlack.png",
    color: "01-SmallColor.png",
    alt: "test1",
    width: 633,
    height: imageHeight,
    active: false,
  },
  {
    id: 2,
    black: "02-SmallBlack.png",
    color: "02-SmallColor.png",
    alt: "test2",
    width: 317,
    height: imageHeight,
    active: false,
  },
  {
    id: 3,
    black: "03-SmallBlack.png",
    color: "03-SmallColor.png",
    alt: "test3",
    width: 1029,
    height: imageHeight,
    active: false,
  },
  {
    id: 4,
    black: "04-SmallBlack.png",
    color: "04-SmallColor.png",
    alt: "test4",
    width: 296,
    height: imageHeight,
    active: false,
  },
  {
    id: 5,
    black: "05-SmallBlack.png",
    color: "05-SmallColor.png",
    alt: "test5",
    width: 478,
    height: imageHeight,
    active: false,
  },
  {
    id: 6,
    black: "06-SmallBlack.png",
    color: "06-SmallColor.png",
    alt: "test6",
    width: 461,
    height: imageHeight,
    active: false,
  },
  {
    id: 7,
    black: "07-SmallBlack.png",
    color: "07-SmallColor.png",
    alt: "test7",
    width: 756,
    height: imageHeight,
    active: false,
  },
  {
    id: 8,
    black: "08-SmallBlack.png",
    color: "08-SmallColor.png",
    alt: "test8",
    width: 643,
    height: imageHeight,
    active: false,
  },
  {
    id: 9,
    black: "09-SmallBlack.png",
    color: "09-SmallColor.png",
    alt: "test9",
    width: 643,
    height: imageHeight,
    active: false,
  },
  {
    id: 10,
    black: "10-SmallBlack.png",
    color: "10-SmallColor.png",
    alt: "test10",
    width: 756,
    height: imageHeight,
    active: false,
  },
  {
    id: 11,
    black: "11-SmallBlack.png",
    color: "11-SmallColor.png",
    alt: "test11",
    width: 643,
    height: imageHeight,
    active: false,
  },
  {
    id: 12,
    black: "12-SmallBlack.png",
    color: "12-SmallColor.png",
    alt: "test12",
    width: 534,
    height: imageHeight,
    active: false,
  },
  {
    id: 13,
    black: "13-SmallBlack.png",
    color: "13-SmallColor.png",
    alt: "test13",
    width: 1021,
    height: imageHeight,
    active: false,
  },
  {
    id: 14,
    black: "14-SmallBlack.png",
    color: "14-SmallColor.png",
    alt: "test14",
    width: 735,
    height: imageHeight,
    active: false,
  },
  {
    id: 15,
    black: "15-SmallBlack.png",
    color: "15-SmallColor.png",
    alt: "test15",
    width: 637,
    height: imageHeight,
    active: false,
  },
  {
    id: 16,
    black: "16-SmallBlack.png",
    color: "16-SmallColor.png",
    alt: "test16",
    width: 575,
    height: imageHeight,
    active: false,
  },
  {
    id: 17,
    black: "17-SmallBlack.png",
    color: "17-SmallColor.png",
    alt: "test17",
    width: 641,
    height: imageHeight,
    active: false,
  },
  {
    id: 18,
    black: "18-SmallBlack.png",
    color: "18-SmallColor.png",
    alt: "test18",
    width: 748,
    height: imageHeight,
    active: false,
  },
];
